#!/bin/bash

export ARCH=arm64
export SUBARCH=arm64
export DTC_EXT=/home/disty/bin/dtc
export TARGET_PREBUILT_KERNEL=Image.gz-dtb

if [$1 == ""]
then
    echo CLEAN OUT
    rm out -rf
    mkdir out

    echo DEFCONFIG
    make  O=out ARCH=arm64 toco_user_defconfig

#    echo MENUCONFIG
#    make O=out menuconfig
fi

PATH="/home/disty/Apps/android/android-clang/clang-bootstrap/bin:/home/disty/Apps/android/aarch64-linux-android-4.9/bin:${PATH}" \
make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-android- \
                      | tee kernel.log

#/home/disty/Apps/android/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin
#/home/disty/Apps/android/android-clang/clang-bootstrap/bin
