#!/bin/bash

mkdir enhance

for i in *.png
do
	enhance $i
	mv $i-2x.jpg "enhance/${i/.jpg}-2x.jpg"
done

for i in *.jpg
do
	enhance $i
	mv $i-2x.jpg "enhance/${i/.jpg}-2x.jpg"
done

for i in *.jpeg
do
	enhance $i
	mv $i-2x.jpg "enhance/${i/.jpeg}-2x.jpg"
done

for i in *.webp
do
	enhance $i
	mv $i-2x.jpg "enhance/${i/.webp}-2x.jpg"
done

