#!/bin/bash

mkdir enhance

for i in *.png
do
	enhance-4x $i
	mv $i-4x.jpg "enhance/${i/.jpg}-4x.jpg"
done

for i in *.jpg
do
	enhance-4x $i
	mv $i-4x.jpg "enhance/${i/.jpg}-4x.jpg"
done

for i in *.jpeg
do
	enhance-4x $i
	mv $i-4x.jpg "enhance/${i/.jpeg}-4x.jpg"
done

for i in *.webp
do
	enhance-4x $i
	mv $i-4x.jpg "enhance/${i/.webp}-4x.jpg"
done

