#!/bin/bash
gnuplot -p << eor
set datafile separator ","
set key autotitle columnhead
set y2tics
set ytics nomirror
plot "hypernetwork_loss.csv" using 1:4 with lines, '' using 1:5 with lines axis x1y2
eor

