#!/bin/bash

EXTRA=$@
PWD=$(pwd)

cd /home/disty/Apps/AI/KoboldAI/
git pull origin
git submodule update
/home/disty/Apps/AI/KoboldAI/play-ipex.sh $EXTRA --host #--no_ui #--model PygmalionAI_pygmalion-6b
cd $PWD
