#!/bin/bash

EXTRA=$@
PWD=$(pwd)
source /opt/intel/oneapi/setvars.sh
/home/disty/Apps/AI/koboldcpp/koboldcpp --useclblast 2 0 --smartcontext --stream --blasbatchsize 1024 $EXTRA --gpulayers 128 #--model /home/disty/Apps/AI/koboldcpp/models/Wizard-Vicuna-13B-Uncensored.ggmlv3.q4_1.bin
#30B-Uncensored.ggmlv3.q2_K.bin
#13B-Uncensored.ggmlv3.q4_1.bin
