#!/bin/bash

for n in *.webm
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.webm$ ]]
   then echo "youtube ${n: -16: 11}" >> IDs
   fi
done

for n in *.mkv
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.mkv$ ]]
   then echo "youtube ${n: -15: 11}" >> IDs
   fi
done

for n in *.mp4
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.mp4$ ]]
   then echo "youtube ${n: -15: 11}" >> IDs
   fi
done

for n in *.mp3
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.mp3$ ]]
   then echo "youtube ${n: -15: 11}" >> IDs
   fi
done

for n in *.opus
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.opus$ ]]
   then echo "youtube ${n: -16: 11}" >> IDs
   fi
done

for n in *.m4a
do if [[ "$n" =~ -[-_0-9a-zA-Z]{11}.m4a$ ]]
   then echo "youtube ${n: -15: 11}" >> IDs
   fi
done


