#!/bin/bash

EXTRA="--use-ipex --listen --insecure --auth-file /home/disty/Apps/AI/automatic/webui-user.bat"
PWD=$(pwd)
cd /home/disty/Apps/AI/automatic
git pull origin
git submodule update
/home/disty/Apps/AI/automatic/webui.sh $EXTRA $@
cd $PWD
