#!/bin/bash
source /opt/intel/oneapi/setvars.sh
#source /opt/intel/oneapi/compiler/latest/env/vars.sh
#source /opt/intel/oneapi/mkl/latest/env/vars.sh

EXTRA=$@
PWD=$(pwd)

cd /home/disty/Apps/automatic
/home/disty/Apps/automatic/webui.sh --use-ipex --listen $EXTRA
cd $PWD
