#!/bin/bash

mkdir Flac

for file in *.wav
do

ffmpeg -i "$file" -n "${file/.wav}.flac"

TITLE=${file/.wav}
TITLE=${TITLE:3}

echo "TITLE=$TITLE
ARTIST=
DATE=
COMMENT=Converted from Wav to FLAC using ffmpeg
ALBUM=
TRACKNUMBER=${file: 0: 2}" > "${file/.wav}.meta"

metaflac --import-picture-from="JKT.png" --import-tags-from="${file/.wav}.meta" "${file/.wav}.flac"

rm "${file/.wav}.meta"

mv "${file/.wav}.flac" Flac/ 
done 
